
Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 99

AllCops:
 Exclude:
   - spec/spec_helper.rb
   - spec/rails_helper.rb
   - db/**/*
   - docs/**/*
   - config/**/*
   - bin/**/*

Metrics/BlockLength:
 Exclude:
   - spec/**/*
